### ISSUE TITLE
Hosting of platform/services

### ISSUE THREAD

**Issue by udhaymanhas** [pesto-students/juntos-ninja-2-beta#18]
Possible options
- Heroku
- Linode
- DigitalOcean

Factors to consider
- Scaling (horizontal)
- Managing sockets while scaling

**Comment by udhaymanhas** [comment]
While scaling the backend horizontally, WebSockets need something called sticky sessions. The regular REST API is stateless but WebSockets are stateful. So when the application utilizing WebSockets is scaled vertically, the load balancer must be configured to enable sticky sessions. Heroku, Linode can enable sticky sessions. DigitalOcean doesn't support sticky sessions.

Resources:
[Heroku](https://devcenter.heroku.com/articles/session-affinity)
[Linode](https://www.linode.com/docs/guides/configuring-load-balancer-sticky-session/)
[DigitalOcean](https://www.digitalocean.com/community/questions/app-platform-and-sticky-sessions-on-load-balancer)

We can go with either Heroku or Linode.
I cannot suggest a single option out of the two without trying them, and that would require some time.

I think we can test it on both the services when the app is ready and decide then?

**Comment by chirgjn** [comment]
This is great!
Can you look at various pricing tiers for these services and see which will suite our needs better?

This what we know about our workload
- Most of the traffic would be on WebSockets
- Upstream and Downstream traffic should be almost equal
- We are mostly I/O bound as we don't run heavy computations

I did some research[[1]] [[2]] and it seems like we would mostly be bound by memory and file descriptors.
We should be good for the demo with a single instance as we might be able to support about 2000 rooms with around 1 GB of RAM

> when the application utilizing WebSockets is scaled vertically, the load balancer must be configured to enable sticky sessions.
Did you mean to say "horizontally" here?

Can also add some resources on how to scale the jobs up and down (both vertically and horizontally) on these platforms

[1]:https://stackoverflow.com/questions/17448061/how-many-system-resources-will-be-held-for-keeping-1-000-000-websocket-open
[2]:https://stackoverflow.com/questions/2332741/what-is-the-theoretical-maximum-number-of-open-tcp-connections-that-a-modern-lin

**Comment by chirgjn** [comment]
Going with Heroku for now, we can switch later if required
