### ISSUE TITLE
Project Plan

### ISSUE THREAD

**Issue by chirgjn** [pesto-students/juntos-ninja-2-beta#20]
# Frontend Modules and APIs

[Hassan]
User, Auth: Firebase  (9th June afternoon)

[Udhay]
SyncedVideoPlayer: WebSockets, Youtube API : (9th June afternoon)

Chat: WebSockets : Hassan (10th June meeting time)
Room: Chat, SyncedVideoPlayer (10th June Meeting time)
App: Room (TBD)

**Comment by chirgjn** [comment]
[Hassan]
User, Auth: Firebase (9th June evening)

[Udhay]
SyncedVideoPlayer (start): WebSockets, Youtube API : (9th June evening)
Landing Page  (9th June evening)
Figma Screens need to merged into the main repo  (9th June evening)

**Comment by chirgjn** [comment]
[Hassan]
User, Auth: Firebase (10th June evening)

[Udhay]
Plan for SyncedVideoPlayer (10th June 5PM)
[In Review] Landing Page (10th June evening)
[Done] Figma Screens need to merged into the main repo  (9th June evening)


[TBD]
SyncedVideoPlayer: WebSockets, Youtube API
Chat: WebSockets
Room: Chat, SyncedVideoPlayer (10th June Meeting time)
App: Room (TBD)

**Comment by chirgjn** [comment]
[Hassan]
[In Review] User, Auth: Firebase (11th June 3PM)
Chat: WebSockets (11 June 9PM)

[Udhay]
Select Video page (first draft) (11th June evening)
[In Review] Landing page (10th June evening)
[Done] Plan for SyncedVideoPlayer (10th June 5PM)
[Done] Figma Screens need to merged into the main repo  (9th June evening)

[TBD]
SyncedVideoPlayer
Room: Chat, SyncedVideoPlayer
App: Room

**Comment by chirgjn** [comment]
[Hassan]
Sign-in / Sign-up screens (14th June 8PM)
Party page without the video player (15 June 8PM)
[In Review] Chat: WebSockets (11 June 9PM)
[Done] User, Auth: Firebase (11th June 3PM)

[Udhay]
Backend setup on Heroku (15th June 8PM)
Socket Server setup (16th June 3PM)
Auth check using Firebase SDK (17th June 8PM)
[In Review] Select Video page (first draft) (14th June 5PM)
[In Review] Landing page (10th June evening)
[Done] Plan for SyncedVideoPlayer (10th June 5PM)
[Done] Figma Screens need to merged into the main repo  (9th June evening)

[TBD]
[Backend]
Channel
Sync Video
Chat [Hassan]
Room
Auth
[Frontend]
SyncedVideoPlayer
Room: Chat, SyncedVideoPlayer
App: Room
Waiting screen

**Comment by chirgjn** [comment]
[Hassan]
Party page without the video player (15 June 8PM)
[In Review] Sign-in / Sign-up screens (14th June 8PM)
[Done] Chat: WebSockets (11 June 9PM)
[Done] User, Auth: Firebase (11th June 3PM)

[Udhay]
[In Review] Select Video page (15th June 8PM)
[In Review] Landing page (15th June 8PM)
Backend setup on Heroku (16th June 8PM)
Socket Server setup (17th June 3PM)
[Done] Plan for SyncedVideoPlayer (10th June 5PM)
[Done] Figma Screens need to merged into the main repo  (9th June evening)

[TBD]
[Backend]
Auth check using Firebase SDK [Udhay]
Channel
Sync Video
Chat [Hassan]
Room
Auth
[Frontend]
SyncedVideoPlayer
Room: Chat, SyncedVideoPlayer
App: Room
Waiting Screen

[Dropped]
[Backend]
Setup Testing

**Comment by codeAesthetic** [comment]
[Hassan]
[In Review] Auth Module integration (16th June 8 PM)
Party page without the video player (17th June 9PM)
[Done] Sign-in / Sign-up screens (15th June 8PM)
[Done] Chat: WebSockets (11 June 9PM)
[Done] User, Auth: Firebase (11th June 3PM)

[Udhay]
[In Review] Select Video page (15th June 8PM)
[In Review] Landing page (15th June 8PM)
Backend setup on Heroku (17th June 9PM)
Socket Server setup (18th June 3PM)
[Done] Plan for SyncedVideoPlayer (10th June 5PM)
[Done] Figma Screens need to merged into the main repo (9th June evening)

[TBD]
[Backend]
Auth check using Firebase SDK [Udhay]
Channel
Sync Video
Chat [Hassan]
Room
Auth

[Frontend]
SyncedVideoPlayer
Room: Chat, SyncedVideoPlayer
App: Room
Waiting Screen

[Dropped]
[Backend]
Setup Testing

**Comment by chirgjn** [comment]
[Hassan]
[In Review] Auth Module integration (21st June 3PM)
[In Review] Select Video page (22nd June 8PM)
[In Review] Landing page (22nd June 8PM)
[In Review] Party page without the video player (22nd June 9PM)
[In Review] SyncedVideoPlayer, App, Room (23rd June 8PM)
Backend (24th June)
[Done] Sign-in / Sign-up screens (15th June 8PM)
[Done] Chat: WebSockets (11 June 9PM)
[Done] User, Auth: Firebase (11th June 3PM)

[Udhay]
~~[In Progress] Backend setup on Heroku (18th June 3PM)~~
~~Socket Server setup (19th June 8PM)~~
[Done] Plan for SyncedVideoPlayer (10th June 5PM)
[Done] Figma Screens need to merged into the main repo (9th June evening)


[Frontend]
~~Waiting Screen~~

[Dropped]
[Backend]
~~Setup Testing~~
~~Auth check using Firebase SDK [Udhay]~~
~~Channel~~
~~Sync Video~~
~~Chat [Hassan]~~
~~Room~~
~~Auth~~
